Add Prettier Config & Adapt Eslint Config
brafdlog/caspion pull request #497
Opened 2023-09-01 08:58 UTC by Yedidyar

what is the motivation:

https://www.youtube.com/watch?v=Cd-gBxzcsdA

if this or accepted we should add format to git hooks

add run yarn format on all project

2023-09-01 11:39 UTC, baruchiro commented
Thank you!

Even before it is accepted, I'm expecting you to test it is not conflicted with ESLint.

Did you run it and run `yarn lint` afterwards?

Also, I can't see how it helps. No one will change the whole source code.

Instead, I'm asking you to add it with `lint-staged` to incrementally format every file that is touched by someone.

https://bscstudent.netlify.app/ci-checklist/

2023-09-01 15:09 UTC, baruchiro approved these changes
Very good work!

I will test it locally and then I will merge it.

What will be your next task? Contact me

2023-09-01 15:14 UTC, Yedidyar commented
> Very good work!
> 
> I will test it locally and then I will merge it.
> 
> What will be your next task? Contact me

I see that the ci dont work because of the node version what should we do?

2023-09-03 06:20 UTC, baruchiro commented
@Yedidyar we have a task for upgrading the nodeJS version: https://github.com/brafdlog/caspion/issues/464

But it is not a quick task.

You should check the `lint-staged` and find its version that matches the nodeJS v14.

2023-09-03 18:49 UTC, Yedidyar commented
> @Yedidyar we have a task for upgrading the nodeJS version: #464
> 
> But it is not a quick task.
> 
> You should check the `lint-staged` and find its version that matches the nodeJS v14.

[cf4e936](https://github.com/brafdlog/caspion/pull/497/commits/cf4e9365c756ffda64ed2091c3a5fa91a6208129)

2023-09-04 06:45 UTC, baruchiro requested changes
There is still a mismatch between `prettier` and `ESLint`.
When I'm running `yarn prettier --write .` and then `yarn lint`, I see multiple warnings like this:

> ⚠  http://eslint.org/docs/rules/object-curly-newline  Expected a line break before this closing brace src\Store.test.tsx:3:56

I'm navigating to this file (`src/Store.test.tsx:3:56`), formatting it with `prettier`, and it shows me an `ESLint` worning. I'm fixing the `ESLint` warning, and formatting it again, and the warning cames back.

2023-09-04 06:45 UTC, baruchiro commented on package.json
> +    "lint-staged": "^13.3.0",
Version `13.3.0` is actually require node 14, as you can see [here](https://github.com/okonet/lint-staged/blob/v13.3.0/package.json#L17), and we need to take one version down.
```suggestion
    "lint-staged": "~13.2.3",
```

2023-09-07 02:15 UTC, Yedidyar commented
@baruchiro [26c4866](https://github.com/brafdlog/caspion/pull/497/commits/26c4866a902047b7e0454ad23a65eae5ece92b65) see this commit a think it the right approach

2023-09-07 02:18 UTC, Yedidyar commented
> Very good work!
> 
> I will test it locally and then I will merge it.
> 
> What will be your next task? Contact me

I think the next step is to move to using Vite.
what is the specific current version of node?

2023-09-10 09:32 UTC, baruchiro approved these changes

2023-09-10 09:37 UTC, merged